// <auto-generated />
namespace ILUMINACAO_PUBLICA.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class merge : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(merge));
        
        string IMigrationMetadata.Id
        {
            get { return "201403282049273_merge"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
